name: Create tag and trigger deploy
on:
  push:
    branches:
      - feat/container-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  bump:
    name: Create tag and release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Get tag value
        id: tag
        run: |
          TAG="$(grep -oP '^chore\(release\).*\K(\d+\.\d+\.\d+)' <<< "$MESSAGE")"
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
      - name: Create and push tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push https://x-access-token:${{ github.token }}@github.com/$GITHUB_REPOSITORY --tags
      - name: Create release
        uses: lidofinance/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
      # Publish container image to github packages
      - name: Log in to the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.tag }}

  deploy-trigger:
    needs: bump
    name: Trigger build and PR creation in the infra-mainnet
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    uses: ./.github/workflows/ci-prod.yml
    secrets: inherit
    with:
      tag: ${{ needs.bump.outputs.tag }}
